openapi: 3.0.2
info:
  title: 'Pass API'
  version: '0.1'
paths:
  /api/submitData/:
    get:
      summary: Возвращает список перевалов
      operationId: listPass
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pass'
          description: 'Успех'
      tags:
      - pass
    post:
      summary: Создает новый перевал
      operationId: createPass
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pass'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pass'
          description: 'Успех'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pass'
          description: 'Bad request'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pass'
          description: 'Ошибка при выполнении операции'
      tags:
      - pass
  /api/submitData/{id}/:
    get:
      summary: Возвращает перевал по его ID
      operationId: retrievePass
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальное целое число, определяющее этот перевал
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pass'
          description: Успех
        '400':
          description: Указан не верный ID (например, не число)
        '404':
          description: Перевал с указанным ID не найден
        'default':
          description: Непредвиденная ошибка
      tags:
      - pass
    patch:
      summary: Частично изменяет перевал c ID
      operationId: partialUpdatePass
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальное целое число, определяющее этот перевал
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pass'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pass'
          description: Успех
        '400':
          description: Указан не верный ID (например, не число)
        '404':
          description: Перевал с указанным ID не найден
        'default':
          description: Непредвиденная ошибка
      tags:
      - pass

components:
  schemas:
    Passage:
      type: object
      title: Pass
      description: Перевал
      properties:
        id:
          type: integer
          format: int64
          description: Уникальное целое число, определяющее этот перевал
          readOnly: true
        beauty_title:
          type: string
          description: Тип, вид объекта (пер., перевал)
          maxLength: 255
        title:
          type: string
          description: Название перевала
          maxLength: 255
        other_titles:
          type: string
          description: иные названия
          maxLength: 255
        connect:
          type: string
          format: text
          description: Что связывает
        author:
          $ref: '#/components/schemas/Climber'
        coords:
          $ref: '#/components/schemas/Coords'
        level:
          $ref: '#/components/schemas/Category'
        images:
          type: file
          title: List of images
          description: Список фотографий перевала
        add_time:
          type: string
          format: timezone
          description: Дата и время добавления
          readOnly: true
        status:
          type: string
          maxLength: 8
          description: 'Статус модерации. Допустимые значения: "new", "pending", "accepted", "rejected"'
      required:
      - title
      - author

    Climber:
      type: object
      title: Climber
      description: Пользователь
      properties:
        email:
          type: string
          format: email
          maxLength: 128
          description: Адрес электронной почты
        fam:
          type: string
          maxLength: 64
          description: Фамилия
        name:
          type: string
          maxLength: 30
          description: Имя
        otc:
          type: string
          maxLength: 30
          description: Отчество
        phone:
          type: string
          minLength: 11
          maxLength: 12
          description: Номер телефона
      required:
        - email
        - fam
        - name
        - phone

    Coords:
      type: object
      title: Coords
      description: Координаты
      properties:
        latitude:
          type: number
          format: float
          description: Широта
        longitude:
          type: number
          format: float
          description: Долгота
        height:
          type: integer
          description: Высота

    Category:
      type: object
      title: Category
      description: Уровни сложности
      properties:
        winter:
          type: string
          maxLength: 2
          description: 'Уровень сложности для зимы. Допустимые значения: "", "1a", "1b", "2a", "2b", "3a", "3b"'
        summer:
          type: string
          maxLength: 2
          description: 'Уровень сложности для лета. Допустимые значения: "", "1a", "1b", "2a", "2b", "3a", "3b"'
        autumn:
          type: string
          maxLength: 2
          description: 'Уровень сложности для осени. Допустимые значения: "", "1a", "1b", "2a", "2b", "3a", "3b"'
        spring:
          type: string
          maxLength: 2
          description: 'Уровень сложности для весны. Допустимые значения: "", "1a", "1b", "2a", "2b", "3a", "3b"'
