openapi: 3.0.2
info:
  title: 'MountainPass API'
  description: "Данная версия учебная и не несёт в себе никакой конкретной информации!"
  version: '1'
paths:
  /perevall/:
    get:
      summary: Перевалы
      description: 'Возвращает список перевалов. Который можно посмотреть на странице http://127.0.0.1:8000/pereval/ '
      operationId: listperevall
      parameters: []
      responses:
        '200':
          description: 'успешно'
          content:
            application/json:
              schema:
                title: successfully
                type: object
                properties:
                  placeholder:
                    type: string
                    description: 'зер гуд вольдемар'

      tags:
        - perevall
    post:
      summary:  новый перевал
      operationId: createperevall
      description: 'Создает новфй перевал'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/perevall'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/perevall'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/perevall'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/perevall'
          '405':
            description: Invalid input
          '400':
            description: Bad Request
      tags:
        - perevall
  /perevall/{id}/:
  get:
      summary: Поиск по ID
      operationId: retrieveperevall
      description: 'Возвращает перевал по его ID'
      parameters:
      - name: id
        in: path
        required: true
        description: 'Уникальное целое число, определяющее этот перевал'
        schema:
          type: integer
      responses:
        '200' :
          $ref: '#/components/schemas/perevall'
          description: Успех
        '404':
          description: 'не успешно'
          content:
            text/plain:
              schema:
                title: Not found
                type: string
                example: Not found
        '500':
          description: 'неправильный ввод данных'
          content:
            application/json:
              schema:
                title: error
                description: 'Ошибка при выполнении операции'
      tags:
        - perevall
  patch:
      summary: Изменение перевала
      operationId: partialUpdate
      description: 'Частично изменяет перевал c ID'
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальное целое число, определяющее этот перевал
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/perevall'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/perevall'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/perevall'
      responses:
        '200' :
          $ref: '#/components/schemas/perevall'
          description: Успех
        '404' :
          description: Перевал с указанным ID не найден
      tags:
      - perevall

perevall/?author__email={email}/:
get:
      summary: Получить список перевалов с фильтром по почте
      description: perevall/?author__email={email}/
      operationId: findPerevalsByEmail
      parameters:
              - name: mail
                in: query
                description: Для фильтрации нужна почта.
                required: true
                schema:
                  type: string
      respons:
              '200':
                description: 'успешно'
                content:
                  application/json:
                    schema:
                      title: successfully
                      type: object
                      properties:
                        placeholder:
                          type: string
                          description: 'зер гуд вольдемар'
      tags:
         - perevall


components:
  schemas:
    perevall:
      type: object
      title: perevall
      description: Перевал
      properties:
        id:
          type: integer
          format: int64
          description: Уникальное целое число, определяющее этот перевал
          readOnly: true
        beautyTitle:
          type: string
          description: Тип, вид объекта (перевал, ущелье, плато)
          enum: [перевал, ущелье, плато]
          maxLength: 7
        title:
          type: string
          description: Название перевала
          maxLength: 150
        other_titles:
          type: string
          description: иные названия
          maxLength: 150
        connect:
          type: string
          format: text
          description: соединяет
        category:
          $ref: '#/components/schemas/Category'
        images:
          $ref: '#/components/schemas/Images'
        add_time:
          type: string
          format: timezone
          description: Дата и время добавления
          readOnly: true
        coords:
          $ref: '#/components/schemas/Coords'
        author:
          $ref: '#/components/schemas/Climber'
        status:
          type: string
          enum:
              - new
              - pending
              - accepted
              - rejected
          default: new
          maxLength: 8
          description: 'Статус модерации. Допустимые значения: "new", "pending", "accepted", "rejected"'

    Climber:
      type: object
      title: Climber
      description: Пользователь
      properties:
        email:
          type: string
          format: email
          maxLength: 128
          description: Адрес электронной почты
        fam:
          type: string
          maxLength: 30
          example: Иванов
          description: Фамилия
        name:
          type: string
          maxLength: 30
          example: Иван
          description: Имя
        otc:
          type: string
          maxLength: 30
          example: Иваныч
          description: Отчество
        phone:
          type: string
          minLength: 11
          maxLength: 12
          example: 88002000500
          description: Номер телефона

    Coords:
      type: objects
      title: Coords
      description: Координаты
      properties:
        latitude:
          type: number
          format: float
          maxLength: 9
          example: 75.123456
          description: Широта
        longitude:
          type: number
          format: float
          maxLength: 9
          example: 75,123456
          description: Долгота
        height:
          type: integer
          maxLength: 5
          example: 12345
          description: Высота

    Category:
      type: objects
      title: Category
      description: 'Уровень сложности для зимы. Допустимые значения: "", "1a", "1b", "2a", "2b", "3a", "3b"'
      properties:
        winter:
          type: string
          $ref: '#/components/schemas/Level'
        summer:
          type: string
          $ref: '#/components/schemas/Level'
        autumn:
          type: string
          $ref: '#/components/schemas/Level'
        spring:
          type: string
          $ref: '#/components/schemas/Level'

    Level:
      type: string
      enum:
        - 1A
        - 1B
        - 2A
        - 2B
        - 3A
        - 3B

    Images:
      type: object
      title: Images
      description: Фотографии перевала
      properties:
        title:
          type: string
          description: Название
          maxLength: 50
        data:
          type: string
          format: url
          description: Ссылка на фотографию

    '200':
      description: 'успешно'
      content:
        application/json:
          schema:
            title: successfully
            type: object
            properties:
              placeholder:
                type: string
                description: 'зер гуд вольдемар'

